eureka:
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka
    fetch-registry: false
    register-with-eureka: false
server:
  port: 20000
spring:
  application:
    name: city_server