server:
  port: 8081
spring:
  application:
    name: hotel
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotel?serverTimezone=GMT&2B8
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka